
if [ "$LANGUAGE-$COUNTRY" == "vi-VN" ]; then
wifi_text_1="Danh sách mạng"
wifi_text_2="Chọn mạng Wi-Fi bất kỳ để thử tìm mật khẩu, ưu tiên WI-FI có chữ WPS vì dễ hack"
wifi_text_3="Bắt đầu kết nối"
wifi_text_4="Không tìm thấy mạng Wi-Fi nào."
wifi_text_5="Mật khẩu đã lưu"
wifi_text_6="Không tìm thấy mật khẩu đã lưu."
STR_ADVANCED_CUSTOM="Tùy chỉnh nâng cao"
STR_OPTION="Tùy chọn"
STR_ALL_ATTACK_METHODS="Kết hợp tất cả các phương thức"
STR_BASIC_ATTACK="Tấn công cơ bản"
STR_PIN_DATABASE_ATTACK="Tấn công bằng cơ sở dữ liệu PIN"
STR_WPS_PUSH_ATTACK="Tấn công bằng nút nhấn (WPS)"
STR_PIN_WARNING="Nhập đúng mã PIN sẽ tăng cơ hội kết nối thành công"
STR_INPUT_PIN="Nhập mã PIN"
STR_PIN_CODE="Mã PIN"
elif [ "$LANGUAGE-$COUNTRY" == "hu-HU" ]; then
wifi_text_1="Hálózatlista"
wifi_text_2="Válasszon ki egy tetszőleges Wi-Fi hálózatot a jelszó megkereséséhez, lehetőleg olyat, amelyiken van „WPS”, mivel azt könnyebb feltörni."
wifi_text_3="Kezdje el a kapcsolatteremtést"
wifi_text_4="Nem található Wi-Fi-hálózat."
wifi_text_5="Mentett jelszavak"
wifi_text_6="Nem található mentett jelszó."
STR_ADVANCED_CUSTOM="Speciális testreszabás"
STR_OPTION="Beállítások"
STR_ALL_ATTACK_METHODS="Kombinálja az összes módszert"
STR_BASIC_ATTACK="Alaptámadás"
STR_PIN_DATABASE_ATTACK="PIN-adatbázis elleni támadás"
STR_WPS_PUSH_ATTACK="Gombnyomásos támadás (WPS)"
STR_PIN_WARNING="A helyes PIN-kód megadása növeli a sikeres csatlakozás esélyét"
STR_INPUT_PIN="Adja meg a PIN-kódot"
STR_PIN_CODE="PIN kód"
elif [ "$LANGUAGE-$COUNTRY" == "es-ES" ]; then
wifi_text_1="Lista de redes"
wifi_text_2="Elige cualquier red Wi-Fi para intentar averiguar la contraseña; se recomiendan las que tienen WPS, ya que son más fáciles de acceder"
wifi_text_3="Iniciar conexión"
wifi_text_4="No se ha encontrado ninguna red Wi-Fi."
wifi_text_5="Contraseñas guardadas"
wifi_text_6="No se ha encontrado ninguna contraseña guardada."
STR_ADVANCED_CUSTOM="Personalización avanzada"
STR_OPTION="Opción"
STR_ALL_ATTACK_METHODS="Combinar todos los métodos"
STR_BASIC_ATTACK="Método básico"
STR_PIN_DATABASE_ATTACK="Método con base de datos de PIN"
STR_WPS_PUSH_ATTACK="Método por botón (WPS)"
STR_PIN_WARNING="Introducir el PIN correcto aumenta las probabilidades de conectar con éxito"
STR_INPUT_PIN="Introduce el código PIN"
STR_PIN_CODE="Código PIN"
elif [ "$LANGUAGE-$COUNTRY" == "zh-CN" ]; then
wifi_text_1="网络列表"
wifi_text_2="选择任意一个 Wi-Fi 网络尝试破解密码，优先选择带有 WPS 标识的网络，因为更容易破解"
wifi_text_3="开始连接"
wifi_text_4="未找到任何 Wi-Fi 网络。"
wifi_text_5="已保存的密码"
wifi_text_6="未找到已保存的密码。"
STR_ADVANCED_CUSTOM="高级自定义"
STR_OPTION="选项"
STR_ALL_ATTACK_METHODS="组合所有攻击方式"
STR_BASIC_ATTACK="基础攻击"
STR_PIN_DATABASE_ATTACK="PIN 码数据库攻击"
STR_WPS_PUSH_ATTACK="按键式攻击（WPS）"
STR_PIN_WARNING="输入正确的 PIN 码可提高连接成功率"
STR_INPUT_PIN="输入 PIN 码"
STR_PIN_CODE="PIN 码"
fi
