
if [ "$LANGUAGE-$COUNTRY" == "vi-VN" ]; then
lang_action_warn="Add-on này có tác dụng sao chép các tệp tin đã chọn vào module magisk, ksu, apatch v.v, để tạo ra module, sau khi khởi động lại nó sẽ được áp dụng vào hệ thống giống như các module khác."
lang_title="Nhập tệp tin"
lang_summary_path="Đường dẫn: "
lang_desc_adb="Điền vị trí đường dẫn, nếu bỏ trống sẽ tự tìm kiếm tên tệp tin khớp với tên trong hệ thống"
lang_desc_prop="Thêm prop vào module"
lang_save_at="Lưu ở: "
lang_searching="Tìm kiếm đường dẫn..."
lang_not_found="Không tìm thấy tệp tin: "
lang_input_notice=", hãy nhập đường dẫn để tạo mới"
lang_del_tile="Xoá tệp nhanh"
lang_del_desc="Lựa chọn tệp tin bất kỳ trong module để xóa bỏ"
lang_del_desc2="Xoá tệp tin bất kỳ trong:"
list_modul="Danh sách tệp được áp dụng"
elif [ "$LANGUAGE-$COUNTRY" == "hu-HU" ]; then
lang_action_warn="Ez a kiegészítő a kijelölt fájlokat egy Magisk-, KSU- vagy APatch-modulba másolja; újraindítás után a modul ugyanúgy aktiválódik a rendszerben, mint bármely más modul."
lang_title="Fájl importálása"
lang_summary_path="Link: "
lang_desc_adb="Adja meg a fájl elérési útját; ha üresen hagyja, a rendszer automatikusan megkeresi a rendszerben lévővel megegyező fájlnevet"
lang_desc_prop="Adj hozzá egy tulajdonságot a modulhoz"
lang_save_at="Mentés ide: "
lang_searching="Útvonal keresése..."
lang_not_found="A fájl nem található: "
lang_input_notice=", adja meg az elérési utat egy új létrehozásához"
lang_del_tile="Fájlok gyors törlése"
lang_del_desc="Válassza ki a törölni kívánt fájlt a modulon belül"
lang_del_desc2="Töröljön bármilyen fájlt a következő helyről:"
list_modul="Alkalmazott fájlok listája"
elif [ "$LANGUAGE-$COUNTRY" == "es-ES" ]; then
lang_action_warn="Este complemento copia los archivos seleccionados a un módulo de Magisk, KSU, APatch, etc., para crear el módulo; tras reiniciar, se aplicará al sistema igual que cualquier otro módulo."
lang_title="Importar archivo"
lang_summary_path="Ruta: "
lang_desc_adb="Introduce la ruta; si se deja en blanco, se buscará automáticamente un nombre de archivo que coincida con el del sistema"
lang_desc_prop="Añadir prop al módulo"
lang_save_at="Guardar en: "
lang_searching="Buscando ruta..."
lang_not_found="Archivo no encontrado: "
lang_input_notice=", introduce la ruta para crear uno nuevo"
lang_del_tile="Eliminación rápida de archivos"
lang_del_desc="Selecciona cualquier archivo del módulo para eliminarlo"
lang_del_desc2="Eliminar cualquier archivo en:"
list_modul="Lista de archivos aplicados"
elif [ "$LANGUAGE-$COUNTRY" == "zh-CN" ]; then
lang_action_warn="此插件会将所选文件复制到 Magisk、KSU、APatch 等模块中以创建新模块，重启后将像其他模块一样应用到系统中。"
lang_title="导入文件"
lang_summary_path="路径："
lang_desc_adb="输入文件路径，若留空将自动查找与系统匹配的文件名"
lang_desc_prop="向模块添加 prop"
lang_save_at="保存至："
lang_searching="正在查找路径…"
lang_not_found="未找到文件："
lang_input_notice="，请输入路径以创建新文件"
lang_del_tile="快速删除文件"
lang_del_desc="选择模块内任意文件进行删除"
lang_del_desc2="删除以下位置的任意文件："
list_modul="已应用文件列表"
fi
